apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce #Apenas um pod por vezes por ler/escrever
  gcePersistentDisk:
    pdName: pv-disk
    fsType: ext4 # Especifique o tipo de sistema de arquivos desejado
  storageClassName: standard